### ISSUE TITLE
Fix redirect issue

### ISSUE THREAD

**Issue by meiqimichelle** [meiqimichelle/mhertzfeld#22]
`this old site looks like it should redirect or something; http://meiqimichelle.github.io/mhertzfeld/   -- found it on google b4 yr new site!`

**Comment by meiqimichelle** [comment]
With #25 and #26, this should be resolved. However, it might take a little bit for google to catch up. I'll leave this open as a placeholder to check in on things in a few weeks.

**Comment by konklone** [comment]
I still see a bunch of uses of the old `github.io` subdomain path in the site resources and metadata:

![image](https://cloud.githubusercontent.com/assets/4592/12079385/ee46b7ac-b204-11e5-9d60-a64cc1c57452.png)

Facebook in particular takes `og:url` really seriously and considers it a redirect during OpenGraph processing.

**Comment by meiqimichelle** [comment]
Hmmm, I may have had my wires crossed there @konklone . I thought the meta info and resources (well, resources in particular) needed to refer directly to the github url because of `baseurl` strangeness with gh-pages. So, what you're seeing is what I intentionally coded, but I'll take another look later today. Thx, as always!

**Comment by meiqimichelle** [comment]
_Sigh._ Well, it's good you flagged this because while looking into this issue, I'm finding all sorts of other things that I never fixed with my meta tags. Up up and away! Fix fix fix......

**Comment by meiqimichelle** [comment]
Whelp, in fixing all the other things, I think this got fixed, too. ie, now the vanity url path seems to work in all the meta/resource paths. I'm gonna go with it for now -- and again check back in on a google search for my name in a week or so.

**Comment by konklone** [comment]
Hmm, offhand I can't think of any reason why you would need to refer to the `github.io` URLs in any way for the site. michellehertzfeld.com is the real URL, not a "vanity" URL! :) **_LIVE PROUD_**

**Comment by meiqimichelle** [comment]
:fist:

**Comment by meiqimichelle** [comment]
Checking in on this, just a few weeks later ;) I think I'm good to go 😆 . Closing.

@konklone 👋
